name: Update Release List

on:
  #release:
  #  types: [published]
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types: [completed]

env:
  # Account for committing
  USER_NAME: "ctags-win32 CI"
  USER_EMAIL: "ctags-win32-ci@users.noreply.github.com"

  # Escape sequences
  COL_RED: "\x1b[31m"
  COL_GREEN: "\x1b[32m"
  COL_YELLOW: "\x1b[33m"
  COL_RESET: "\x1b[m"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        #fetch-depth: 0
        path: main

    - uses: actions/checkout@v2
      with:
        repository: "${{ github.repository }}.wiki"
        path: wiki

    - name: Update Release List
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd main
        #latest=$(git describe --tags --abbrev=0)
        cd ../wiki
        ../main/scripts/update-release-list.py
        git add Releases-in-*.md
        if git diff HEAD --quiet; then
          echo ${COL_YELLOW}No updates.${COL_RESET}
        else
          git config --local user.name ${USER_NAME}
          git config --local user.email ${USER_EMAIL}
          #git commit -a -m "Update Release List to ${latest}"
          git commit -a -m "Update Release List"
          git push origin HEAD
        fi
